#! /bin/zsh

# Inspired by the tutorial and script from Nick Congleton at LinuxConfig.org
# https://linuxconfig.org/how-to-use-ffmpeg-to-convert-multiple-media-files-at-once-on-linux

# Batch convert files to HEVC/H.265 using handbrakeCLI (required) to MKV container.
# Script assumes audio is AAC and passes it through unchanged.

srcExt=$1
srcDir=$2
outDir=${3:-"recompressed"}
qua=${4:-28}

# Check for output directory and create if necessary
if [ ! -d "$outDir" ]; then
mkdir "$srcDir"/"$outDir"
fi

# Count requested files
fileCount="$(find "$srcDir"/*.$srcExt \( ! -regex '.*/\..*' \) -type f | wc -l | tr -d ' ')"

echo "Beginning conversion of $fileCount file(s)."

# Begin conversion
for filename in $srcDir/*.$srcExt; do

basePath=${filename%.*}
baseName=${basePath##*/}

handbrakecli -i "$filename" -e x265 -f av_mkv -q $qua -E copy:aac -o "$srcDir"/"$outDir"/"$baseName".mkv

done

# TBD: Notify on completion via IFTTT (Requires applet configured to receive webhooks)
# curl -X POST https://maker.ifttt.com/trigger/conversion/with/key/$IFTTT_KEY

# Notify on completion via shell
echo "Batch conversion of $fileCount $srcExt files in $srcDir complete!"

# Notify on completion via macOS Notification (Requires terminal-notifier)
terminal-notifier -title bash265 -message "Batch conversion of $fileCount $srcExt files in $srcDir complete!"