#! /bin/zsh

# Inspired by the tutorial and script from Nick Congleton at LinuxConfig.org
# https://linuxconfig.org/how-to-use-ffmpeg-to-convert-multiple-media-files-at-once-on-linux

# Batch convert files to HEVC/H.265 using handbrakeCLI (required) to MKV container.
# Script assumes audio is AAC and passes it through unchanged.

# Usage: Call script with these arguments: 
# 1. Extension of files you want to convert. (ex: mp4)
# 2. Directory of source files.(Files must be in subdirectory of working directory)
# 3. (OPT) Output directory name. (Default is "recompressed".)
# 4. (OPT) Quality setting (0-51. 0 is lossless. 51 is terrible. 28 by default)

# Example commands: 
# $ batch265 mp4 videos

# This will find all files with the extension "mp4" in the subdirectory "videos" of the 
# working directory and convert them to HEVC/H265 with quality 28 and the filetype MKV,
# placing the results in a "recompressed" subdirectory of the "videos" directory.

# $ batch265 m4a "vacation" "archive" 20

# This will find all files with the extension "m4a" in the subdirectory "vacation" of the
# working directory and convert them to HEVC/H265 with quality 20 and the filetype MKV,
# placing the results in the "archive" subdirectory of the "vacation" directory.

srcExt=$1
srcDir=$2
outDir=${3:-"recompressed"}
qua=${4:-28}

# Check for output directory and create if necessary
if [ ! -d "$outDir" ]; then
mkdir "$srcDir"/"$outDir"
fi

# Count requested files
fileCount="$(find "$srcDir"/*.$srcExt \( ! -regex '.*/\..*' \) -type f | wc -l | tr -d ' ')"

echo "Beginning conversion of $fileCount file(s)."

# Begin conversion
for filename in $srcDir/*.$srcExt; do

basePath=${filename%.*}
baseName=${basePath##*/}

handbrakecli -i "$filename" -e x265 -f av_mkv -q $qua -E copy:aac -o "$srcDir"/"$outDir"/"$baseName".mkv

done

# TBD: Notify on completion via IFTTT (Requires applet configured to receive webhooks)
# curl -X POST https://maker.ifttt.com/trigger/conversion/with/key/$IFTTT_KEY

# Notify on completion via shell
echo "Batch conversion of $fileCount $srcExt files in $srcDir complete!"

# Notify on completion via macOS Notification (Requires terminal-notifier)
terminal-notifier -title bash265 -message "Batch conversion of $fileCount $srcExt files in $srcDir complete!"